var GAME_LEVELS = [
  ["                                                                                ",
   "   @      v                           v                                         ",
   "               v                            v                                   ",
   "  x                 v                            v               o              ",
   "  x                                                              xx p           ",
   "  x                                x                          p                 ",
   "  x                      xxxxx                          p  xx        p          ",
   "  x                                                 xx                          ",
   "  x                  xx                        o  p                    p        ",
   "  x                                      xx   xxx                               ",
   "  x              xx                                                     p       ",
   "  x   o                                                                         ",
   "  xxxxx     xx                                                           p   e  ",
   "  x                                                                        xxx  ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                               "],
  ["                                                                                   xxxxxxxxxxxxx",
   "                                                                                   xx           ",
   "    @                                                                         ox   xx         e ",
   "  x   x                              x          vvvvvvvvvvvv                   x   xx     xxxxx ",
   "  x   x                              p                                         x   xx     x vvv ",
   "  x   x                                                                        x   xx     x     ",
   "  x   x                        x                                               x   xx     x     ",
   "  x   x                        p                                               x   xx     x     ",
   "  x   x                                                                        x   xx     x     ",
   "  x   x                                                                        x   xx     x     ",
   "  x   x                   o                                                    x   xx     x     ",
   "  x   x                   x                                                    x   xx     x     ",
   "  x   x                   p                                                   ox   xx     x     ",
   "  x   x                                                                        x   xx     x     ",
   "  x   x              x                                                        ox          x     ",
   "  x   x              p                                                         x          x     ",
   "  x              o                                            p    p    p     ox          x     ",
   "  x              x                           x=            xxxxxxxxxxxxxxxxxxxxx   xxxxxxxx     ",
   "  xxxxxxxxxx     p                           p                                                  ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                "],
   ["                                                                                                                    ",
    "   x                                             x   @   xx    v                                          p     |   ",
    "   x   ppppppppppppppppppppppppppppppppppppppppppx       xx                                               p    |    ",
    "   x                                                     xx                                               p   |     ",
    "   x                                                     xx                                               p  |      ",
    "   x                                                     xx                                               p |       ",
    "   x   =         =         =       =                     xx              xxxxxxxxxxxxxxxxxxxxxxxxxxxx     p|        ",
    "   x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         x     p|        ",
    "   x                                                                x                               x     p |       ",
    "   x                                                                                                x     p  |      ",
    "   x                                                           x                                    x     p   |     ",
    "   x                                                                                                x     p    |    ",
    "   xxxxxxxxxxxxxxxxxxxxxxxxx      x       x       x       x                                         x     p     |   ",
    "   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     p      |  ",
    "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     p       | ",
    "                                                                                                    x     p        |",
    "                                                                                                    x     p        |",
    "                                                                                                    x     p       | ",
    "                                                                                                    x     p      |  ",
    "                                                                                                    x     p     |   ",
    "                                                                                               e    x     p    |    ",
    "                       x      x      x      x      x       x       x      x      x      x      x    x     p   |     ",
    "                x                                                                                   x     p  |      ",
    "            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     p |       ",
    "        x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     p|        ",
    "              v        v         v        v         v         v          v        v        v              p|        ",
    "      x           p                   p                  p                    p                 p         p |       ",
    "                                                                                                          p  |      ",
    "   x                                                                                                      p   |     ",
    "                                                                                                          p    |    ",
    "      x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxpppppp     |   ",
    "                                                                                                                    "],
    ["                                                                                                        ",
     "                                                                                                         ",
     "                                                                                                         ",
     "                                                                                                         ",
     "                                                                                                         ",
     "      p     p   pppppp   p    p        p     p     p   p   p      p    p          p p p    p p p         ",
     "       p   p    p    p   p    p        p    p p    p       p p    p    p        p       p p      p       ",
     "        p p     p    p   p    p        p   p   p   p   p   p  p   p    p         p               p       ",
     "         p      p    p   p    p        p  p     p  p   p   p   p  p    p           p           p         ",
     "         p      p    p   p    p        p p       p p   p   p    p p    p             p       p           ",
     "         p      p    p   p    p        pp         pp   p   p      p                    p   p             ",
     "         p      pppppp   pppppp        p           p   p   p      p    p                 p               ",
     "                                                                                                         ",
     "                                                                                                         ",
     "  @                                                                                                      ",
     " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx e ",
     " ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ",
     "                                                                                                         ",
     " ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ",
    "                                                                                                          "]
    ];

    if (typeof module != "undefined" && module.exports)
      module.exports = GAME_LEVELS;
